[package]
name = "pdl"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rss = "2.0"
reqwest = { version = "0.12", features = ["blocking"] }
indicatif = "0.17"
inquire = "0.7"
anyhow = "1.0"
